In [4]:
import pandas as pd
import regex as re
import numpy as np

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

import transformers
from transformers import pipeline

In [5]:
data = pd.read_csv("book_reviews_sample.csv")
data.head()

   index                                         reviewText  rating
0  11494  Clean and funny. A bit busy with all the diffe...       3
1    984  Alex a sexy hot cop and the PhD candidate. Wha...       4
2   1463  Good thing that this is a free story. I read i...       1
3  10342  Action, action, action! Equipment keeps gettin...       4
4   5256  this was hands down the worse book i have ever...       1

In [6]:
data['reviewText'][0]

'Clean and funny. A bit busy with all the different plots going on. But overall a good read. Bye now.'

In [7]:
data['reviewText_clean'] = data['reviewText'].str.lower()

In [11]:
data['reviewText_clean'] = data['reviewText_clean'].apply(lambda x: re.sub(r'[^\w\s]', '', str(x)))

In [12]:
data.head()

,index,reviewText,rating,reviewText_clean
0,11494,Clean and funny. A bit busy with all the diffe...,3,clean and funny a bit busy with all the differ...
1,984,Alex a sexy hot cop and the PhD candidate. Wha...,4,alex a sexy hot cop and the phd candidate what...
2,1463,Good thing that this is a free story. I read i...,1,good thing that this is a free story i read it...
3,10342,"Action, action, action! Equipment keeps gettin...",4,action action action equipment keeps getting b...
4,5256,this was hands down the worse book i have ever...,1,this was hands down the worse book i have ever...

In [13]:
vader_sentiment = SentimentIntensityAnalyzer()

In [19]:
data['vader_sentiment_score'] = data['reviewText_clean'].apply(lambda review : vader_sentiment.polarity_scores(review)['compound'])

In [20]:
data.head()

,index,reviewText,rating,reviewText_clean,vader_sentiment_score
0,11494,Clean and funny. A bit busy with all the diffe...,3,clean and funny a bit busy with all the differ...,0.7684
1,984,Alex a sexy hot cop and the PhD candidate. Wha...,4,alex a sexy hot cop and the phd candidate what...,0.9325
2,1463,Good thing that this is a free story. I read i...,1,good thing that this is a free story i read it...,0.6740
3,10342,"Action, action, action! Equipment keeps gettin...",4,action action action equipment keeps getting b...,0.6652
4,5256,this was hands down the worse book i have ever...,1,this was hands down the worse book i have ever...,-0.4767

## Bins: the value ranges that define how the scores are divided

In [23]:
bins = [-1,-0.1,0.1,1]
names = ['negative','neutral','positive']

data ['vader_sentiment_label'] = pd.cut(data['vader_sentiment_score'],bins, labels=names)